import { Poppins } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/Provider/AuthProvider/AuthProvider";
import ReactQueryProvider from "@/Provider/QueryProvider/QueryProvider";

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["400", "500", "600", "700"],
});
export const metadata = {
  title: "Enroll Nationwide",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased overflow-hidden`}>
        <ReactQueryProvider>
          <AuthProvider>{children}</AuthProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
