// import { Poppins } from "next/font/google";
// import "./globals.css";
// import AuthProvider from "@/Provider/AuthProvider/AuthProvider";
// import ReactQueryProvider from "@/Provider/QueryProvider/QueryProvider";
// import { Toaster } from "sonner";

// const poppins = Poppins({
//   subsets: ["latin"],
//   variable: "--font-poppins",
//   weight: ["400", "500", "600", "700"],
// });
// export const metadata = {
//   title: "Enroll Nationwide",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={`${poppins.variable} antialiased overflow-hidden`}>
//         <ReactQueryProvider>
//           <Toaster position="top-center" theme="light" />
//           <AuthProvider>{children}</AuthProvider>
//         </ReactQueryProvider>
//       </body>
//     </html>
//   );
// }

import { Poppins } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/Provider/AuthProvider/AuthProvider";
import ReactQueryProvider from "@/Provider/QueryProvider/QueryProvider";
import { Toaster } from "sonner";

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Enroll Nationwide",
  description:
    "Effortlessly Run Your CPR Business: Schedule Classes, Register Attendees, Process Payments, and Distribute Certifications with Ease!",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en">
      <body className={`${poppins.variable} antialiased overflow-hidden bg-light dark:bg-dark`}>
        <ReactQueryProvider>
          <Toaster position="top-right" theme="light" />
          <AuthProvider>{children}</AuthProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}